# Use the MySQL image compatible with ARM architectures
FROM arm64v8/mysql:latest

# Set environment variables
ENV MYSQL_DATABASE=saurav
# ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root
ENV MYSQL_ROOT_PASSWORD=root

# Expose the MySQL port
EXPOSE 3306
